config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  root 'welcom#index'
  
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
 
  get 'signup'=> 'users#new'
  get 'login'=> 'sessions#new'
  post 'login'=> 'sessions#create'
  delete 'logout'=> 'sessions#destroy'
  resources :users
  

end

app/models/user.rb
class User < ActiveRecord::Base
   attr_accessor :remember_token
  before_save {self.email = email.downcase }
  validates :name,presence: true,length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,presence: true,length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
   uniqueness: { case_sensitive: false }
    has_secure_password
     validates :password,length: { minimum: 6 }, allow_nil: true
     before_create { generate_token(:auth_token) }

def send_password_reset
  generate_token(:password_reset_token)
  self.password_reset_sent_at = Time.zone.now
  save!
  UserMailer.password_reset(self).deliver
end

def generate_token(column)
  begin
    self[column] = SecureRandom.urlsafe_base64
  end while User.exists?(column => self[column])
end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
   

  def current_user
      @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
    end
   

   def current_user
      @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
      user = User.find_by(email: params[:session][:email].downcase)
   if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
        redirect_to user
  else
      flash[:danger] ='Invalid email/password combination'# Not quite right!
      # Create an error message.render 'new'
      render 'new'
   end
   end
   def destroy
       log_out
       cookies.delete(:auth_token)
      redirect_to root_url
  end
  def redirect_back_or(default)
      redirect_to(session[:forwarding_url] || default)
      session.delete(:forwarding_url)
  end
      # Stores the URL trying to be accessed.
  def store_location
      session[:forwarding_url] = request.url if request.get?
  end
  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
   if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
   else
      @current_user
   end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,only: [:edit,:update]
  before_action :correct_user,only: [:edit,:update]
  def new
     @user = User.new
  end
  def show
     @user = User.find(params[:id])
  end
  def create
      @user = User.new(user_params)
   if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
   else
       render 'new'
    end
   end
  def edit
      @user = User.find(params[:id])
  end
  def update
      @user = User.find(params[:id])
   if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
  else
      render 'edit'
  end
  end
  private
  def user_params
      params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
   # Stores the URL trying to be accessed
     # Confirms a logged-in user.
  def logged_in_user
  unless logged_in?
     flash[:danger] = "Please log in."
     redirect_to login_url
  end
  end
  def correct_user
     @user = User.find(params[:id])
       # redirect_to(root_url) unless current_user?(@user)
     redirect_to(root_url) unless @user == current_user
end
end

app/controllers/welcom_controller.rb
class WelcomController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
def show_field_error(model, field)
    s=""

    if !model.errors[field].empty?
      s =
        <<-EOHTML
           <div id="error_message">
             #{model.errors[field][0]}
           </div>
        EOHTML
    end

    s.html_safe
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
      session[:user_id] = user.id
  end
  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end
  # Returns true if the user is logged in,false otherwise.
  def logged_in?
      !current_user.nil?
  end
  # Logs out the current user.
  def log_out
       session.delete(:user_id)
      @current_user = nil
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcom_helper.rb
module WelcomHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">  <div class="container"><%= link_to "sample app", root_path, id: "logo" %><nav>      <ul class="nav navbar-nav navbar-right">      <li><%= link_to "Home", root_path %></li>        <li><%= link_to "Help", help_path %></li>         <% if logged_in? %>                   <li><%= link_to "Users", '#' %></li>         <li class="dropdown">            <a href="#" class="dropdown-toggle" data-toggle="dropdown">              Account <b class="caret"></b>          </a>            <ul class="dropdown-menu">                   <li><%= link_to "Profile", current_user %></li>              <li><%= link_to "Settings", edit_user_path(current_user) %></li>              <li class="divider"></li>           <li>    <%= link_to "Log out", logout_path, method: "delete" %> </li>  </ul>   </li> <% else %> <li><%= link_to "Log in", login_path %></li><% end %></ul>    </nav>  </div></header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RahamanApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background:#80BFFF">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<nav class="navbar navbar-inverse">
  <div class="navbar-inner">
<ul class="nav">
<li><%= link_to "Wellcome My Page", controller: 'welcom'%></li>
<li><%= link_to "Users",    '#' %></li>
<li><%= link_to "Settings", '#' %></li>
<li><%= link_to "Profile", users_path(current_user) %></li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<% if logged_in? %>
 <li>
   <%= link_to "Log out", logout_path, method: :delete %></li>
  <li> <%= link_to "Sign up", signup_path  %></li>
 
 <% else %>
 <li><%= link_to "Log in", login_path %></li>
   <li>  <%= link_to "Sign up", signup_path  %></li>
<% end %>
   <% flash.each do |message_type,message| %>
   <%= message %>
   <% end %>
</div>
  </div>
</nav>
<div class="container">
<%= yield %>
</dive>
</body>
</html>

app/views/password_resets/new.html.erb
<h1>PasswordResets#new</h1>
<p>Find me in app/views/password_resets/new.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    The form contains
   <%= pluralize(@user.errors.count,"error") %>
   <ul>
   <% @user.errors.full_messages.each do |msg| %>
   <li><%= msg %></li>
   <% end %>
   </ul>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<%= form_for(@user) do |f| %>
  <%= render'shared/error_messages'%>
  <%= f.label :name %>
  <%= f.email_field :name,class:'form-control'%>
  <%= f.label :email %>
  <%= f.text_field :email,class:'form-control'%>
  <%= f.label :password %>
  <%= f.password_field :password,class:'form-control'%>
  <%= f.label :password_confirmation,"Confirmation" %>
  <%= f.password_field :password_confirmation,class:'form-control'%>
  <%= f.submit "Save changes",class: "btn btn-primary"%>
<% end %>
<div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1> Sign up </h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages'%>
  <%= f.label :name %>
  <%= f.text_field :name ,class:'form-control'%></br>
  <%= f.label :email %>
  <%= f.email_field :email,class:'form-control' %></br>
  <%= f.label :password %>
  <%= f.password_field :password ,class:'form-control'%></br>
  <%= f.label :password_confirmation,"Confirmation" %>
  <%= f.password_field :password_confirmation,class:'form-control' %></br>
  <%=  f.submit 'Sign Up',class: "btn btn-primary" %>&nbsp;&nbsp;&nbsp;
   <%= f.submit 'Clear Form',class: "btn btn-primary",:type => 'reset' %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= @user.name %> <br>
<%= @user.email%>
<%= link_to "Edit Profile", edit_user_path(@user)%>
</div>
</div>

app/views/welcom/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

</head>
<body>

<div class="container">
  <div class="jumbotron">

    <li><h1><big><font color="FF00CC">Wellcom My Sign Up and Sign In</font></big></h1></li>
    <%= link_to "Sign up now!", signup_path  %>
    </br>
<big><big><big><font color="#546f">Assignment  User Authentication in Ruby on Rails </font></big></big></big></br></br>
<big><font color="#546f">Name&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Abdul Rahaman!</font></big></br></br>
<big><font color="#546f">Roll NO &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp 04!</font></big></br></br>
<big><font color="#546f">Class &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspM.c.s!</font></big></br></br>
<big><font color="#546f">Semester&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp 4th!</font></big></br></br>
<big><font color="#546f">Subject &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspRuby On Rails!</font></big></br></br>  <center>
<h2><big><font color="FF00CC"> End !</font></big></big></big></h2></br> </br>  
</center>
 
 </div>
</body>
</html>